[package]
name = "kos-kbot"
version = "0.1.2"
authors = [
    "Benjamin Bolte <ben@kscale.dev>",
    "Denys Bezmenov <denys@kscale.dev>",
    "Jingxiang Mo <jx@kscale.dev>",
    "Pawel Budzianowski <pawel@kscale.dev>",
    "Wesley Maa <wesley@kscale.dev>",
]
edition = "2021"
license = "MIT"
repository = "https://github.com/kscalelabs/kos-kbot"
description = "KOS platform for KBot"

[dependencies]
kos = "0.3"
eyre = "0.6"
krec = "0.2"
tracing = "0.1"
async-trait = "0.1"
robstride = "0.3"
gstreamer = "0.20"
gstreamer-app = "0.20"
gstreamer-video = "0.20"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
[target.'cfg(target_os = "linux")'.dependencies]
imu = ">=0.2.1"
chrono = "0.4"
